name: zEssentialsXConverter
version: 1.0
main: com.github.zEssentialsXConverter.ZEssentialsXConverter
api-version: 1.20
commands:
  convertztoex:
    description: Converts zEssentials data to EssentialsX data.
    usage: /convertztoex
    permission: zessentialstoconverter.convert
